version: '3'
services:

  phpadmin:
    image: 'phpmyadmin/phpmyadmin:latest'
    environment:
      - PMA_HOST=mariadb
      - PMA_PORT=3306
      - PMA_USER=bn_opencart
    ports:
      - '${PHPADMIN_PORT}:80'

  mariadb:
    image: docker.io/bitnami/mariadb:10.3
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=bn_opencart
      - MARIADB_DATABASE=bitnami_opencart
    volumes:
      - 'mariadb_data:/bitnami/mariadb'
    ports:
      - '3306:3306'

  opencart:
    image: docker.io/bitnami/opencart:3
    container_name: opencart
    environment:
      - OPENCART_HOST=localhost
      - OPENCART_EXTERNAL_HTTP_PORT_NUMBER=8080
      - OPENCART_EXTERNAL_HTTPS_PORT_NUMBER=443
      - OPENCART_DATABASE_HOST=mariadb
      - OPENCART_DATABASE_PORT_NUMBER=3306
      - OPENCART_DATABASE_USER=bn_opencart
      - OPENCART_DATABASE_NAME=bitnami_opencart
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - '${OPENCART_PORT}:8080'
      - '443:8443'
    volumes:
      - 'opencart_data:/bitnami/opencart'
      - 'opencart_storage_data:/bitnami/opencart_storage/'
    depends_on:
      - mariadb

  tests:
    build:
      dockerfile: Dockerfile
    environment:
      - PYTHONUNBUFFERED=1
    command: sh -c "sleep 5 && echo http://$HOST_OPENCART:$PORT_OPENCART && pytest -n $THREADS -o log_cli=true  -o log_cli_level=INFO -v --alluredir /app/allure-results  --browser=$BROWSER --url http://$HOST_OPENCART:$PORT_OPENCART"
    volumes:
      - ./allure-results:/app/allure-results
      - ./allure-reports:/app/default-reports
      - ./screenshots:/app/tests/screenshots
    depends_on:
      - opencart
    network_mode: container:opencart

volumes:
  mariadb_data:
    driver: local
  opencart_data:
    driver: local
  opencart_storage_data:
    driver: local
